Intro

In [119]:
import numpy as np

In [25]:
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3]
(3,)
int32
1
3
4


In [ ]:
print(a[0])
a[0] = 10
print(a)

b = a * np.array([2,0,2])
print(b)

1
[10  2  3]
[20  0  6]


Array vs Lists

In [ ]:
l = [1,2,3]
a = np.array([1,2,3])

#l.append(4)
#a.append(4) doesnt work

#l += [4]
#a = a + np.array(([4])) # correctly done[4,4,4]

#l *= 2
#a = a *2

print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [ ]:
#a = np.sqrt(a)
#a = np.log(a)



print(a)

[0.         0.69314718 1.09861229]


Dot Product

In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

dot = np.dot(a1,a2)
print(dot)

#sum1 = a1*a2
#dot = np.sum(sum1)

# easier
dot = (a1*a2).sum()
print(dot)

dot = a1@a2
print(dot)


32
32
32
32


Multidimensional Arrays

In [ ]:
import numpy as np

a = np.array([[1,2], [3,4]])
print(a.shape)

print(a[:,0])

print(a.T)
print(np.linalg.inv(a))
print(np.linalg.det(a))
c = np.diag(a)
print(np.diag(c))

(2, 2)
[1 3]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[[1 0]
 [0 4]]


Slicing

In [ ]:
import numpy as np

a = np.array([[1,2,3,4], 
              [5,6,7,8]])
print(a)

b = a[-1, -2]
print(b)

[[1 2 3 4]
 [5 6 7 8]]
7


In [ ]:
import numpy as np

a = np.array([[1,2],
              [3, 4],
              [5,6]
])
print(a)

print(a[a > 2])

b = np.where(a>2, a, -1)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
import numpy as np

a = np.array([10,19,30,41,50,61])
print(a)
even = np.argwhere(a%2==0).flatten()
print(a[even])

# b = [1,3,5]
# print(a[b])

[10 19 30 41 50 61]
[10 30 50]


Reshaping

In [ ]:
import numpy as np

a = np.arange(1,7)

print(a)
print(a.shape)

#b = a.reshape((3,2))
#print(b)
b = a[:, np.newaxis]
print(b)


[1 2 3 4 5 6]
(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Concatenation

In [ ]:
import numpy as np

#a = np.array([[1,2], [3,4]])
#print(a)
#b = np.array([[5,6]])
#c = np.concatenate((a, b.T), axis=1)
#print(c)

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

#hstack
c = np.vstack((a,b))
print(c)


[[1 2 3 4]
 [5 6 7 8]]


Broadcasting

In [ ]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
a = np.array([1,0,1])
y = x + a
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


Functions and Axis

In [ ]:
import numpy as np

a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])
print(a)
print(a.max(axis=0))

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
[17 18 19 20 21 22 23]


Datatypes

In [ ]:
import numpy as np

x = np.array([1.0,2.0], dtype=np.int64)
print(x)
print(x.dtype)

[1 2]
int64


Copying

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 42
print(b)
print(a)

[42  2  3]
[1 2 3]


Generating Arrays

In [10]:
import numpy as np

a = np.zeros((2,3))
a = np.ones((2,3))
a = np.full((2,3), 5.0)
a = np.eye(3)
a = np.arange(20)
a = np.linspace(0, 10, 5)

print(a)




[ 0.   2.5  5.   7.5 10. ]


Random Numbers

In [17]:
a = np.random.random((3, 2))
a = np.random.randn(1000)
a = np.random.randint(10, size=(3,3))

print(a)

[[6 2 2]
 [0 6 2]
 [0 3 9]]


Linear Algebra

In [22]:
import numpy as np

a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)

print(eigenvalues)
print(eigenvectors)

b = eigenvectors[:,0] * eigenvalues[0]
print(b)
c = a @ eigenvectors[:,0]
print(b)

#print(b==c)
print(np.allclose(b,c))

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
True


In [24]:
# x1 + x2 = 2200 
# 1.5x1 + 4x2 = 5050

A = np.array([[1,1], 
              [1.5,4]])
b = np.array([2200,
              5050])

# Manual Method
x = np.linalg.inv(A).dot(b)

# Numpy way
x = np.linalg.solve(A, b)
print(x)



[1500.  700.]
